.common_branch_config: &common_branch_config
  stage: first-stage
  only:
    - web
  before_script:
    - echo "FAIL" > .job_status
    - curl --request POST -H "content-type:application/json" -d '{"pipelineId":"'${CI_PIPELINE_ID}'","userId":"'${GITLAB_USER_ID}'","userEmail":"'${GITLAB_USER_EMAIL}'","commitName":"'${CI_COMMIT_REF_NAME}'","jobName":"'${CI_JOB_NAME}'","projectName":"'${CI_PROJECT_NAME}'","commitVersion":"'${CI_COMMIT_SHA}'","jobId":"'${CI_JOB_ID}'","startTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'","date":"'"$(date +%Y-%m-%d)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/putCIParams
  after_script:
    - curl --request POST -H "content-type:application/json" -d '{"jobId":"'${CI_JOB_ID}'","endTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'","date":"'"$(date +%Y-%m-%d)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/updateEndTime
    - >
      if [ $(cat .job_status) != 'SUCCESS' ]; then
        curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/reportEngineBuildComplete.sh -o reportEngineBuildComplete.sh
        sh reportEngineBuildComplete.sh $GITLAB_USER_EMAIL $CI_COMMIT_REF_NAME 1
      fi
  tags:
    - shared

stages:
  - start-stage
  - first-stage
  - end-stage

BuildEngineMac:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine_new.py -o trigger_cloud_build_engine_new.py
    - python3 -u trigger_cloud_build_engine_new.py $CI_COMMIT_REF_NAME mac
    - echo "SUCCESS" > .job_status

BuildEngineLinux:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine_new.py -o trigger_cloud_build_engine_new.py
    - python3 -u trigger_cloud_build_engine_new.py $CI_COMMIT_REF_NAME linux
    - echo "SUCCESS" > .job_status

ExecuteOnEnd:
  stage: end-stage
  only:
    - web
  retry: 2
  tags:
    - shared
  script:
    - curl --request POST -H "content-type:application/json" -d '{"pipelineId":"'${CI_PIPELINE_ID}'","endTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/reportEndTime
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/reportEngineBuildComplete.sh -o reportEngineBuildComplete.sh
    - sh reportEngineBuildComplete.sh $GITLAB_USER_EMAIL $CI_COMMIT_REF_NAME 0

ExecuteOnStart:
  stage: start-stage
  only:
    - web
  retry: 2
  tags:
    - shared
  script:
    - curl --request POST -H "content-type:application/json" -d '{"pipelineId":"'${CI_PIPELINE_ID}'","userId":"'${GITLAB_USER_ID}'","userEmail":"'${GITLAB_USER_EMAIL}'","commitName":"'${CI_COMMIT_REF_NAME}'","projectName":"'${CI_PROJECT_NAME}'","commitVersion":"'${CI_COMMIT_SHA}'","startTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'","date":"'"$(date +%Y-%m-%d)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/reportStartTime