stages:  
  - test

# 定义 job
unittests:
  stage: test
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/unittests/unittests.py -o unittests.py
    - python3 unittests.py --branch="$CI_COMMIT_REF_NAME"
  tags:
    - flutter