.common_branch_config: &common_branch_config
  stage: first-stage
  only:
    - web
  retry: 2
  tags:
    - shared

.protect_branch_config: &protect_branch_config
  stage: first-stage
  only:
    - bd_1.22
  retry: 2
  tags:
    - shared

stages:
  - first-stage
  - end-stage

# 定义 job
#unittests:
#  stage: first-stage
#  except:
#    - web
#  script:
#    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/unittests/unittests.py -o unittests.py
#    - python3 unittests.py -b $CI_COMMIT_REF_NAME -c $CI_COMMIT_SHA
#  tags:
#    - flutter


WebBuildEngineMacAndroid:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_android

WebBuildEngineLinuxAndroid:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME linux_android


WebBuildEngineMacIos:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_ios


WebBuildLitesAndLiteg:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME lites_and_liteg


reportOnEnd:
  <<: *common_branch_config
  stage: end-stage
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/reportEngineBuildComplete.sh -o reportEngineBuildComplete.sh
    - sh reportEngineBuildComplete.sh $GITLAB_USER_EMAIL $CI_COMMIT_REF_NAME


AutoBuildEngineMacAndroid:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_android

AutoBuildEngineLinuxAndroid:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME linux_android


AutoBuildEngineMacIos:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_ios


AutoBuildLitesAndLiteg:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME lites_and_liteg


AutoReportOnEnd:
  <<: *protect_branch_config
  stage: end-stage
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/reportEngineBuildComplete.sh -o reportEngineBuildComplete.sh
    - sh reportEngineBuildComplete.sh $GITLAB_USER_EMAIL $CI_COMMIT_REF_NAME