.common_branch_config: &common_branch_config
  stage: first-stage
  only:
    - web
  retry: 2
  tags:
    - shared

.protect_branch_config: &protect_branch_config
  stage: first-stage
  only:
    - bd_1.22
  except:
    - web
  retry: 2
  tags:
    - shared

stages:
  - first-stage
  - end-stage

# 定义 job
#unittests:
#  stage: first-stage
#  except:
#    - web
#  script:
#    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/unittests/unittests.py -o unittests.py
#    - python3 unittests.py -b $CI_COMMIT_REF_NAME -c $CI_COMMIT_SHA
#  tags:
#    - flutter


WebBuildEngineMacAndroid:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_android_build

WebBuildEngineMacAndroidLite:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_android_lite_build

WebBuildEngineLinuxAndroid:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME linux_android_build

WebBuildEngineLinuxAndroidLite:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME linux_android_lite_build

WebBuildEngineMacIos:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_ios_build

WebBuildEngineMacIosLite:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_ios_lite_build

WebBuildEngineHostMac:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME host_mac_build

WebBuildEngineHostLinux:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME host_linux_build

reportOnEnd:
  <<: *common_branch_config
  stage: end-stage
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/reportEngineBuildComplete.sh -o reportEngineBuildComplete.sh
    - sh reportEngineBuildComplete.sh $GITLAB_USER_EMAIL $CI_COMMIT_REF_NAME


AutoBuildEngineMacAndroid:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_android_build

AutoBuildEngineMacAndroidLite:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_android_lite_build

AutoBuildEngineLinuxAndroid:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME linux_android_build

AutoBuildEngineLinuxAndroidLite:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME linux_android_lite_build

AutoBuildEngineMacIos:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_ios_build

AutoBuildEngineMacIosLite:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_ios_lite_build

AutoBuildEngineHostMac:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME host_mac_build

AutoBuildEngineHostLinux:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME host_linux_build


AutoReportOnEnd:
  <<: *protect_branch_config
  stage: end-stage
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/reportEngineBuildComplete.sh -o reportEngineBuildComplete.sh
    - sh reportEngineBuildComplete.sh $GITLAB_USER_EMAIL $CI_COMMIT_REF_NAME