.common_branch_config: &common_branch_config
  stage: first-stage
  only:
    - web
  before_script:
    - curl --request POST -H "content-type:application/json" -d '{"pipelineId":"'${CI_PIPELINE_ID}'","userId":"'${GITLAB_USER_ID}'","userEmail":"'${GITLAB_USER_EMAIL}'","commitName":"'${CI_COMMIT_REF_NAME}'","jobName":"'${CI_JOB_NAME}'","projectName":"'${CI_PROJECT_NAME}'","commitVersion":"'${CI_COMMIT_SHA}'","jobId":"'${CI_JOB_ID}'","startTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'","date":"'"$(date +%Y-%m-%d)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/putCIParams
  after_script:
    - curl --request POST -H "content-type:application/json" -d '{"jobId":"'${CI_JOB_ID}'","endTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'","date":"'"$(date +%Y-%m-%d)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/updateEndTime
  retry: 2
  tags:
    - shared

.protect_branch_config: &protect_branch_config
  stage: first-stage
  only:
    - bd_1.22
  before_script:
    - curl --request POST -H "content-type:application/json" -d '{"pipelineId":"'${CI_PIPELINE_ID}'","userId":"'${GITLAB_USER_ID}'","userEmail":"'${GITLAB_USER_EMAIL}'","commitName":"'${CI_COMMIT_REF_NAME}'","jobName":"'${CI_JOB_NAME}'","projectName":"'${CI_PROJECT_NAME}'","commitVersion":"'${CI_COMMIT_SHA}'","jobId":"'${CI_JOB_ID}'","startTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'","date":"'"$(date +%Y-%m-%d)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/putCIParams
  after_script:
    - curl --request POST -H "content-type:application/json" -d '{"jobId":"'${CI_JOB_ID}'","endTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'","date":"'"$(date +%Y-%m-%d)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/updateEndTime
  except:
    - web
  retry: 2
  tags:
    - shared

stages:
  - start-stage
  - first-stage
  - end-stage

# 定义 job
#unittests:
#  stage: first-stage
#  except:
#    - web
#  script:
#    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/unittests/unittests.py -o unittests.py
#    - python3 unittests.py -b $CI_COMMIT_REF_NAME -c $CI_COMMIT_SHA
#  tags:
#    - flutter


WebBuildEngineMacAndroid:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_android_build

WebBuildEngineMacAndroidLite:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_android_lite_build

WebBuildEngineLinuxAndroid:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME linux_android_build

WebBuildEngineLinuxAndroidLite:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME linux_android_lite_build

WebBuildEngineMacIos:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_ios_build

WebBuildEngineMacIosLite:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_ios_lite_build

WebBuildEngineHostMac:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME host_mac_build

WebBuildEngineHostLinux:
  <<: *common_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME host_linux_build

reportOnEnd:
  stage: end-stage
  only:
    - web
  retry: 2
  tags:
    - shared
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/reportEngineBuildComplete.sh -o reportEngineBuildComplete.sh
    - sh reportEngineBuildComplete.sh $GITLAB_USER_EMAIL $CI_COMMIT_REF_NAME
  after_script:
    - curl --request POST -H "content-type:application/json" -d '{"pipelineId":"'${CI_PIPELINE_ID}'","endTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/reportEndTime

ReportOnStart:
  stage: start-stage
  only:
    - web
  retry: 2
  tags:
    - shared
  script:
    - curl --request POST -H "content-type:application/json" -d '{"pipelineId":"'${CI_PIPELINE_ID}'","userId":"'${GITLAB_USER_ID}'","userEmail":"'${GITLAB_USER_EMAIL}'","commitName":"'${CI_COMMIT_REF_NAME}'","projectName":"'${CI_PROJECT_NAME}'","commitVersion":"'${CI_COMMIT_SHA}'","startTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'","date":"'"$(date +%Y-%m-%d)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/reportStartTime

AutoBuildEngineMacAndroid:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_android_build

AutoBuildEngineMacAndroidLite:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_android_lite_build

AutoBuildEngineLinuxAndroid:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME linux_android_build

AutoBuildEngineLinuxAndroidLite:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME linux_android_lite_build

AutoBuildEngineMacIos:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_ios_build

AutoBuildEngineMacIosLite:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME mac_ios_lite_build

AutoBuildEngineHostMac:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME host_mac_build

AutoBuildEngineHostLinux:
  <<: *protect_branch_config
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/trigger_cloud_build_engine.py -o trigger_cloud_build_engine.py
    - python3 -u trigger_cloud_build_engine.py $CI_COMMIT_REF_NAME host_linux_build


AutoReportOnEnd:
  stage: end-stage
  only:
    - bd_1.22
  except:
    - web
  retry: 2
  tags:
    - shared
  script:
    - curl -s http://tosv.byted.org/obj/toutiao.ios.arch/flutter/reportEngineBuildComplete.sh -o reportEngineBuildComplete.sh
    - sh reportEngineBuildComplete.sh $GITLAB_USER_EMAIL $CI_COMMIT_REF_NAME
  after_script:
    - curl --request POST -H "content-type:application/json" -d '{"pipelineId":"'${CI_PIPELINE_ID}'","endTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/reportEndTime

AutoReportOnStart:
  stage: start-stage
  only:
    - bd_1.22
  except:
    - web
  retry: 2
  tags:
    - shared
  script:
    - curl --request POST -H "content-type:application/json" -d '{"pipelineId":"'${CI_PIPELINE_ID}'","userId":"'${GITLAB_USER_ID}'","userEmail":"'${GITLAB_USER_EMAIL}'","commitName":"'${CI_COMMIT_REF_NAME}'","projectName":"'${CI_PROJECT_NAME}'","commitVersion":"'${CI_COMMIT_SHA}'","startTime":"'"$(date +%Y-%m-%dT%H:%M:%S)"'","date":"'"$(date +%Y-%m-%d)"'"}' https://cloudapi.bytedance.net/faas/services/ttxnzk/invoke/reportStartTime